modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Mozilla Public License 2.0"

[[mods]]
modId = "extradevices"
version = "${version}"
displayName = "ExtraDevices"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.extradevices]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extradevices]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extradevices]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"
